/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ArchIcon {
        /**
          * The svg icon css classes 'svg-icon--selected' - Active class 'svg-icon--without-hover' - Icon without interaction 'svg-icon--without-fill' - Icon without add a fill color (keep original fill color)
         */
        "classes": string;
        /**
          * The svg icon name
         */
        "svg": string;
    }
    interface ArchLoader {
    }
}
declare global {
    interface HTMLArchIconElement extends Components.ArchIcon, HTMLStencilElement {
    }
    var HTMLArchIconElement: {
        prototype: HTMLArchIconElement;
        new (): HTMLArchIconElement;
    };
    interface HTMLArchLoaderElement extends Components.ArchLoader, HTMLStencilElement {
    }
    var HTMLArchLoaderElement: {
        prototype: HTMLArchLoaderElement;
        new (): HTMLArchLoaderElement;
    };
    interface HTMLElementTagNameMap {
        "arch-icon": HTMLArchIconElement;
        "arch-loader": HTMLArchLoaderElement;
    }
}
declare namespace LocalJSX {
    interface ArchIcon {
        /**
          * The svg icon css classes 'svg-icon--selected' - Active class 'svg-icon--without-hover' - Icon without interaction 'svg-icon--without-fill' - Icon without add a fill color (keep original fill color)
         */
        "classes"?: string;
        /**
          * The svg icon name
         */
        "svg"?: string;
    }
    interface ArchLoader {
    }
    interface IntrinsicElements {
        "arch-icon": ArchIcon;
        "arch-loader": ArchLoader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "arch-icon": LocalJSX.ArchIcon & JSXBase.HTMLAttributes<HTMLArchIconElement>;
            "arch-loader": LocalJSX.ArchLoader & JSXBase.HTMLAttributes<HTMLArchLoaderElement>;
        }
    }
}
